name: sparsearray2d
description: A sparse 2 dimenstional array.
version: 0.1.0
repository: https://github.com/derbec/sparsearray2d

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
